source "http://rubygems.org"
gem 'daemon-kit'
gem 'amqp', :git =>"git://github.com/tmm1/amqp.git"
gem 'ruote', :git => 'git://github.com/jmettraux/ruote.git', :branch => 'ruote2.1'
gem 'ruote-amqp', :git => "git://github.com/kennethkalmer/ruote-amqp.git", :branch => 'ruote2.1'
gem 'rspec'
gem 'eventmachine'
gem 'json'
gem 'yajl-ruby'