
source 'http://rubygems.org'

gem 'rspec'

gem 'json'
gem 'yajl-ruby'
gem 'daemon-kit'
gem 'ruote', :git => 'git://github.com/jmettraux/ruote.git'
gem 'ruote-amqp', :git => 'git://github.com/kennethkalmer/ruote-amqp.git'

